### ISSUE TITLE
Precision in MaCS 

### ISSUE THREAD

**Issue by ismael2395** [gchen98/macs#39]
Hello @gchen98, 

I was wondering if there was any way of increasing the precision (say, to 10 significant digits) of the coalescent times in the trees produced from MaCS? 

Thanks, 
Ismael

**Comment by gchen98** [comment]
I don't think there would be a portable, straightforward way beyond what we are doing.  Ideally we would store in 32 bit floats for speed, but right now heights (e.g. coal times) are already stored as 64 bit doubles.

**Comment by ismael2395** [comment]
Thanks for your response @gchen98!
