### ISSUE TITLE
Issues with Building macs--Compiling

### ISSUE THREAD

**Issue by KeyuXu** [gchen98/macs#41]
There is an error "In file included from simulator.cpp:7:
./simulator.h:8:9: fatal error: 'boost/weak_ptr.hpp' file not found
#include<boost/weak_ptr.hpp>
        ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [simulator.o] Error 1"
when I try to make macs.
Can you help me to solve this problem?

**Comment by gchen98** [comment]
You may want to edit the path in your makefile:

https://github.com/gchen98/macs/blob/master/makefile

for entry:
LIB = -I /Users/garychen/software/boost_1_36_0

Change that directory to a path on your installation and verify that boost/weak_ptr.hpp is there.
