### ISSUE TITLE
GSR certificate for MaCS

### ISSUE THREAD

**Issue by BoPeng** [gchen98/macs#42]
Hi, @gchen98  The [GSR](https://popmodels.cancercontrol.cancer.gov/gsr/) team has evaluated MaCS as part of the GSR certification program but we could not reach you through your usc email address. Could you please write to gsr@mail.nih.gov and let us know your current contact information? Thanks.

**Comment by gchen98** [comment]
Hi Bo, I've sent the e-mail with my update.  Thanks.
